/**
 * Parity gate: TS crypto must reproduce / open artifacts the Python build wrote.
 * Fixtures live in ./fixtures and are generated by
 *   scripts/gen_ts_parity_fixtures.py in the Python orbkey repo.
 */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { describe, it, expect } from 'vitest';
import * as crypto from '../../src/core/crypto.js';
import type { KmsClientLike } from '../../src/core/crypto.js';

const here = dirname(fileURLToPath(import.meta.url));
const fx = (name: string): Record<string, unknown> =>
  JSON.parse(readFileSync(join(here, 'fixtures', name), 'utf-8'));
const b64 = (s: unknown): Buffer => Buffer.from(String(s), 'base64');

describe('crypto parity with Python', () => {
  it('Argon2id derives the same key for a known vector', () => {
    const v = fx('kdf_vector.json');
    const params = crypto.argon2ParamsFromJson(
      v.params as { time_cost: number; memory_cost: number; parallelism: number },
    );
    const key = crypto.deriveKey(String(v.password), b64(v.salt_b64), params);
    expect(key.toString('hex')).toBe(b64(v.expected_key_b64).toString('hex'));
  });

  it('unpacks a Python-written local blob', () => {
    const v = fx('local_blob.json');
    const out = crypto.unpackLocalBlob(b64(v.key_b64), b64(v.blob_b64));
    expect(out.equals(b64(v.plaintext_b64))).toBe(true);
  });

  it('local blob round-trips byte-identically in framing (version+nonce+ct)', () => {
    const key = crypto.randomKey();
    const pt = Buffer.from('hello parity');
    const blob = crypto.packLocalBlob(key, pt);
    expect(blob[0]).toBe(crypto.LOCAL_FORMAT_VERSION);
    expect(blob.length).toBe(1 + crypto.NONCE_SIZE + pt.length + crypto.TAG_SIZE);
    expect(crypto.unpackLocalBlob(key, blob).equals(pt)).toBe(true);
  });

  it('decrypts a Python checkpoint blob to the serialized image', () => {
    const v = fx('checkpoint.json');
    const image = crypto.unpackLocalBlob(b64(v.db_key_b64), b64(v.checkpoint_b64));
    // SQLite images start with the "SQLite format 3\0" magic.
    expect(image.subarray(0, 16).toString('latin1')).toBe('SQLite format 3\0');
  });

  it('decrypts a Python KMS-enveloped remote blob via a replaying mock KMS', async () => {
    const v = fx('kms_blob.json');
    const wrapped = b64(v.wrapped_b64);
    const dataKey = b64(v.data_key_b64);
    const mockKms: KmsClientLike = {
      generateDataKey() {
        throw new Error('not needed for decrypt');
      },
      async decrypt(input) {
        // Replay: only the recorded wrapped blob maps to the recorded data key.
        if (!Buffer.from(input.CiphertextBlob).equals(wrapped)) {
          throw new Error('unexpected wrapped blob');
        }
        return { Plaintext: dataKey };
      },
    };
    const image = await crypto.kmsDecrypt(mockKms, b64(v.remote_blob_b64));
    expect(image.subarray(0, 16).toString('latin1')).toBe('SQLite format 3\0');
  });
});
